import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Piano from "@/components/Piano";
import Player from "@/components/Player";
import PianoRoll from "@/components/PianoRoll";
import PianoRollControl from "@/components/PianoRollControl";
import {
	BsFillPlayFill,
	BsFillStopFill,
	BsFillRecordFill,
	BsFillTrashFill,
} from "react-icons/bs";
import Metronome from "@/components/Metronome";
import { useRef } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const melody = useRef();
	return (
		<>
			<Head>
				<title>Midi Visualizer</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="grid grid-cols-5 h-[800px] gap-4 p-10">
				<h1 className="col-span-1 col-start-2 justify-self-center self-center">
					<Metronome />
				</h1>

				<PianoRollControl melodyRef={melody.current} />

				<div className="col-span-3 col-start-2 justify-self-center self-center max-h-full max-w-full overflow-x-scroll overflow-y-scroll">
					<PianoRoll />
				</div>
				<div></div>
			</div>
			{/* <Piano /> */}
			{/* <Player /> */}
		</>
	);
}
